const { chromium } = require('./browser.cjs');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: {width: 1440, height: 1000} });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => {if (m.type() === 'error') errors.push(m.text());});
  const origin = 'http://127.0.0.1:4174';
  const headings = {index:'It starts with',acoustics:'Less echo.',energy:'From shell',vision:'There’s still a use'};
  for (const [name,heading] of Object.entries(headings)) {
    const response = await page.goto(`${origin}/${name}.html`);
    await page.evaluate(() => document.fonts.ready);
    assert.equal(response.status(), 200);
    assert.equal(new URL(page.url()).pathname, name === 'index' ? '/' : `/${name}`);
    assert((await page.locator('h1').innerText()).includes(heading));
    assert(response.headers()['content-security-policy'].includes("script-src 'self'"));
    await page.reload();assert((await page.locator('h1').innerText()).includes(heading));
  }
  await page.goto(origin+'/acoustics#lab');
  await page.locator('[data-simulation]').waitFor();
  await page.locator('#structure').fill('85');
  assert.equal(await page.locator('#structure-value').textContent(),'COMPACT');
  await page.locator('[data-step="8"]').click();
  assert.equal(await page.locator('.process-text h3').textContent(),'Compression');
  await page.locator('[data-open-brief]').click();
  await page.locator('[data-create-brief]').click();
  await page.locator('#brief-text').fill('Deployment check: edited brief.');
  const pending = page.waitForEvent('download');await page.locator('#download-brief').click();
  const download = await pending;
  assert.equal(fs.readFileSync(await download.path(),'utf8'),'Deployment check: edited brief.');
  await page.locator('#interest').selectOption('energy');
  assert.equal(await page.locator('#download-brief').count(),0);
  await page.keyboard.press('Escape');
  await page.goto(origin+'/');
  await page.locator('[data-separate]').click();
  assert.equal(await page.locator('[data-separate]').getAttribute('aria-pressed'),'true');
  await page.locator('.try-links a[href="energy.html#lab"]').click();
  await page.waitForURL('**/energy.html#lab');await page.locator('[data-simulation=energy]').waitFor();
  await page.reload();assert.equal(new URL(page.url()).pathname,'/energy');
  assert.equal(await page.locator('[data-simulation=energy]').count(),1);
  assert.deepEqual(errors,[]);
  const response=await page.goto(origin+'/missing/page');
  assert.equal(response.status(),404);
  assert((await page.locator('h1').innerText()).includes('Nothing here.'));
  assert.equal(await page.locator('a[href="/"]').count(),2);
  await page.screenshot({path:path.join(__dirname,'../screenshots/404-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(__dirname,'../screenshots/404-mobile.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await browser.close();
  console.log('PASS: deploy artifact, HTML-to-clean-URL redirects, page refreshes, CSP, interactions, edited downloads, direct model links and custom 404.');
})().catch(error=>{console.error(error);process.exit(1)});
